function Footer({ website }) {

  return (

    <footer className="
    bg-black
    text-white
    py-10
    ">


      <div className="
      max-w-7xl
      mx-auto
      px-6
      text-center
      ">


        <h2 className="
        text-3xl
        font-bold
        ">
          {website.title}
        </h2>


        <p className="
        mt-4
        text-gray-400
        ">
          {website.location}
        </p>


        <p className="
        mt-6
        text-gray-500
        ">
          Generated by DigitalLaunch AI 🚀
        </p>


      </div>


    </footer>

  );

}


export default Footer;